PhxConscious/instawesome

- package.json
- src/App.js
- src/Components/Forms/LandingPage.js
- src/Components/Header.js
- src/Components/LMS/Dashboard.js
- src/Components/Layout.js
- src/Components/Main.js
- src/Components/Reusable/LmsCard.js
- src/Styles/HeaderStyles.css
- src/Styles/LmsCardStyles.css
- src/Styles/LmsCardsStyles.css
- src/config/unit-cards.js
- src/config/unitCards.js
- src/config/userProgress.js
I'm getting the router flow set up. Don't be shocked by an ugly header and a little more component hierarchy. I'm keeping App.js bare with Layout.js as the only component returned. Layout is designed to keep the permanent components - one could be a header (that's there always. maybe just a hamburger menu), another could be the main content shown. I made a Main.js component as the switchboard for all of the content. 
Layout looks like this:
```
<div>
<Header />
<Main />
</div>
```
I'm also adding a component for the LMS dashboard
> Lms react router setup

- src/Components/Reusable/LmsCard.js
- src/Styles/LmsCardStyles.css
Puts the icon in for completed or uncompleted. Also fixes up the css a bit more. Flex box is the shit!
> adds check mark and css sweep

- README.md
> adds three spaces to readme

- package.json
- src/Components/LMS/CheckTasks.js
- src/Components/LMS/Dashboard.js
- src/Components/LMS/LessonContent.js
- src/Components/LMS/LessonHeader.js
- src/Components/LMS/MultipleChoice.js
- src/Components/LMS/TrueFalseContent.js
- src/Components/LMS/VideoContent.js
- src/Styles/LmsCardsStyles.css
- src/config/unitCards.js
- src/config/userProgress.js
We need to make the content on the right half of the page relate to the selected unit on the left side.
> Lms add lesson content window

- src/Components/LMS/CheckTasks.js
- src/Components/LMS/Dashboard.js
- src/Components/LMS/LessonContent.js
- src/Components/Reusable/LmsCard.js
- src/Styles/CheckTasks.css
- src/Styles/LmsCardStyles.css
- src/config/unitCards.js
- src/config/userProgress.js
brings in array length into CheckTasks component so we can render some kind of status update to user for how of lesson remains.
also:
puts the locked icon on the units the user don't have access to.
> Lms locks uncompleted units and starts lessons task status bar

- package.json
- src/App.js
- src/Components/Forms/LandingPage.js
- src/Components/Forms/RecoverUsername.js
- src/Components/Header.js
- src/Components/LMS/CheckTasks.js
- src/Components/LMS/Dashboard.js
- src/Components/LMS/LessonContent.js
- src/Components/Layout.js
- src/Components/Main.js
- src/Components/Reusable/AppNav.js
- src/Components/Reusable/GreenFormContainer.js
- src/Components/Reusable/LmsCard.js
- src/redux/reducers/index.js
- src/redux/reducers/userProgress.js
- src/redux/stores/index.js
basic redux implementation with no functionality
> Lms brings in redux & fixes console errors

- src/Components/LMS/CheckTasks.js
- src/Components/LMS/Dashboard.js
- src/Components/LMS/LessonContent.js
- src/Components/LMS/LessonHeader.js
- src/config/unitCards.js
- src/config/userProgress.js
per conversation with Kyle, we need to have a 'lesson' layer. I'm redoing almost everything to put that in.
> Lms makes lesson layer between unit and questions

- src/Components/LMS/CheckTasks.js
- src/Components/LMS/Dashboard.js
- src/redux/actions/userProgress.js
- src/redux/reducers/userProgress.js
the buttons need to hook up to redux state. I'm trying to bring redux into the whole flow
> Lms fixes buttons on check box component and layout

- src/Components/LMS/CheckTasks.js
- src/Components/LMS/Dashboard.js
- src/Components/LMS/LessonContent.js
- src/Components/LMS/LessonHeader.js
- src/redux/actions/lmsContent.js
- src/redux/actions/userProgress.js
- src/redux/reducers/userProgress.js
* bring server requests into app rather than static data
* make buttons and display on CheckTasks component work
> Tie redux more into lesson flow

- src/Components/LMS/CheckTasks.js
- src/Components/LMS/Dashboard.js
- src/Components/LMS/LessonContent.js
- src/redux/actions/lmsContent.js
- src/redux/reducers/userProgress.js
Was experiencing a a currentQuestionObj what was decreasing in length each time the next question button was clicked. In the end I just did a GET for the lmsContent on every click
> Tie redux more into lesson flow 2

- src/Components/LMS/CheckTasks.js
- src/Components/LMS/Dashboard.js
- src/Components/LMS/LessonContent.js
- src/Components/LMS/LessonHeader.js
- src/Components/LMS/checktasksbackup.js
- src/redux/actions/currentValues.js
- src/redux/reducers/currentValues.js
- src/redux/reducers/index.js
* remove almost all setState functions
* change state.xxxxx references to reference props(redux)
* fix lifecycle methods that are affected
> Lms put current objs into redux

- src/Components/LMS/CheckTasks.js
- src/Components/LMS/Dashboard.js
* get checkbox to reflect status of question completion
* disable next button if checkbox is not checked
* make prev and next buttons visibility corrent depending on index of questions/lessons arrays
> Lms check task update to use redux current values

- src/Components/LMS/CheckTasks.js
- src/Components/LMS/Dashboard.js
Goal is to begin on unit1/lesson1/question1 and click next until last question of last unit
> Lms make next question button cycle lessons & units

- src/Components/LMS/CheckTasks.js
- src/Components/LMS/Dashboard.js
* make prevQuestion and prevLesson buttons work
* add edge cases to them so they dont provoke errors
* make the unit cards on left clickable
> Lms/ wire up "previous" for unit,lesson,question

- src/Components/LMS/Checkbox.js
- src/Components/LMS/ContentBody.js
- src/Components/LMS/Dashboard.js
- src/Components/LMS/LessonContent.js
- src/Components/LMS/LessonHeader.js
- src/Styles/LmsComponentsStyles.css
* makes lessonIcons to show user progress 
* makes checkbox a separate component
* make checktasks separate component
> Lms/ css on check tasks

- src/Components/Forms/SignIn.js
- src/Components/Forms/SignUp.js
- src/Components/LMS/Dashboard.js
- src/Components/Pages/SignUp.js
- src/Components/Pages/UserProfile.js
* .then functions need to have a callback or they don't work right.  @IsmaelPerezGit  @chrisjannenga
> Fixes the createUserWithEmailAndPassword in login

- .idea/workspace.xml
- src/Components/Forms/Company.js
- src/Components/Forms/SignUp.js
- src/redux/actions/companyInfo.js
- src/redux/actions/userCompanyJoin.js
- src/redux/reducers/companyInfo.js
- src/redux/reducers/index.js
- src/redux/reducers/userCompanyJoin.js
Haven't been able to make the company form functional. So far, I've set up the redux portion but am not completely sure I'm taking the right approach. Lets discuss it when theres a chance.
> started setting up user company join in redux.

- src/Components/Forms/SignIn.js
- src/Components/LMS/Dashboard.js
- src/redux/actions/companyInfo.js
- src/redux/actions/userCompanyJoin.js
- src/redux/actions/userProgress.js
- src/redux/reducers/companyInfo.js
- src/redux/reducers/userCompanyJoin.js
I've had some hacky setTimeout functions and a click event that came from a modal in order to make the redux data flow work in the lms. Time to take out the ghetto parts
> Lms: remove "start learning" modal

- src/Components/Forms/Company.js
*GOT RID OF A SETTIMEOUT! its a new way of chaining actions without Thunk*
> Company: makes chained action reducer (userCompanyJoin - createCompany)

- src/Components/Forms/SignIn.js
- src/Components/Pages/Splash.js
- src/Components/Reusable/AppNav.js
* handle removal of cookie 
* reference firebase upon user return to site
> fixes logout

- src/Components/Main.js
- src/Components/Pages/Feedback.js
- src/Components/Reusable/AppNav.js
- src/redux/actions/feedback.js
- src/redux/reducers/feedback.js
- src/redux/reducers/index.js
* actions  
* reducers
* build feedback component
> Feedback/ creates the functionality for user to leave feedback

- src/App.css
- src/Components/LMS/ContentBody.js
- src/Components/LMS/MultiChoiceAnswer.js
- src/Components/LMS/MultiChoiceShell.js
- src/Styles/ContentBodyStyles.css
- src/Styles/MultiChoiceStyles.css
Now the basic component exists and I think it will work as the user goes through multiple questions, althought it's untested because I only put one new question into the LMS content data. 
I was thinking, @IsmaelPerezGit, that this is a pretty good opportunity for you to see how the LMS is wired up. There are a couple more updates that haven't been made to the system for it to reflect the spreadsheet that Jeremy made.
The most important is getting the button to display the ```userOptions(s) / userOption ``` columns in the spreadsheet on the buttons. I don't think it'll be crazy complicated but between that and working with the content data, I think you can see how it's pieced together. 
Let me know if you want me to explain any of the madness that is on these pages...
> Lms/ add multichoice question component

- package.json
- src/Components/LMS/ContentBody.js
- src/Components/LMS/Dashboard.js
- src/Components/LMS/MultiChoiceShell.js
- src/Styles/ContentBodyStyles.css
- src/Styles/DashboardStyles.css
react-mdl dialog boxes aren't supported by firefox or safari.
> Implement react modal

- .gitignore
- README.md
- package-lock.json
- package.json
- src/config.js
- src/constants/server.js
- src/index.js
- src/redux/actions/companyInfo.js
- src/redux/actions/feedback.js
- src/redux/actions/lmsContent.js
- src/redux/actions/userCompanyJoin.js
- src/redux/actions/userExpertJoin.js
- src/redux/actions/userProgress.js
Check the README on instructions for how to use the new `tmp/ENV` file.  This will control configuration details such as the firebase credentials, and the web address of the UI and API.
> modify app to use tmp/ENV

- README.md
- package.json
- src/Components/Forms/SignIn.js
- src/config.js
- src/redux/actions/companyInfo.js
- src/redux/actions/feedback.js
- src/redux/actions/lmsContent.js
- src/redux/actions/userCompanyJoin.js
- src/redux/actions/userExpertJoin.js
- src/redux/actions/userProgress.js
Since the `tmp/ENV` file was causing problems I've removed it and the values will now be determined automatically based on whether `NODE_ENV` is `production` or `development`.  I also fixed a typo that was causing the XHRs not to load - I had accidentally used a #{} for interpolation instead of a ${}.
The project should run as you're used to now without any extra steps.
> config now determined automatically based on environment

- src/Components/Pages/ExpertDashboard.js
adds more info to expert panel by bringing in userCompanyJoin info
> ExpertDashboard: brings in company info

- public/index.html
This is a fucking test to see if I can get this shit right!!!!
> This is a test.

- src/Components/Admin/UserOverview.js
- src/utils/helper.js
now renders an easier to read unit and lesson title
> Admin and expert fixup

- src/Components/Pages/AdminDashboard.js
- src/Components/Pages/ExpertDashboard.js
prevents unauthorized users from viewing admin or expert panels
> AdminDashboard ExpertDashboard: adds permissions for render protection

- src/Components/Admin/CommentFeed.js
- src/Components/Forms/Feedback.js
- src/Components/Main.js
- src/Components/Pages/Forum.js
- src/Components/Reusable/AppNav.js
- src/redux/actions/feedback.js
- src/redux/reducers/feedback.js
* makes feedback posting and comment feed in same page
* stops overcalling of API
* resets redux store.feedback upon loading the page so it's always fresh
@chrisjannenga
> Integrate feedback and forum & fixes bugs in CommentFeed

- src/Components/Main.js
- src/Components/Pages/Payment.js
- src/Components/Reusable/AppNav.js
Maybe we need to do the hard sell here? and then give the opportunity to purchase?
@chrisjannenga
> Stripe implementation

- .idea/workspace.xml
- package.json
- src/Components/LMS/ContentBody.js
- src/Components/LMS/CopyTextInput.js
- src/Components/LMS/TextInput.js
- src/Styles/ContentBodyStyles.css
- src/Styles/FormsStyles.css
- yarn.lock
ContentBody: Added CopyTextInput component to LMS question that requires copy to clipboard.
> CopyTextInput: Added component that allows user to copy to clipboard.

- src/Components/Pages/Payment.js
- src/Components/Payment/BuyInsta3200.js
- src/Components/Payment/Receipt.js
- src/Components/Reusable/AppNav.js
- src/Styles/ReceiptStyles.css
- src/redux/actions/payments.js
- src/redux/actions/userProgress.js
- src/redux/reducers/index.js
- src/redux/reducers/payments.js
- src/redux/reducers/userProgress.js
* brings all payment info into redux - we can show all payments later etc
* adds a screen for promo and fine print with a click-to-buy button
* after click goes to a receipt page
* user is upgrated to isInstaStud: true
**** no other updates have been made to conditionally render for isInstaStud. We should think about permissions and make a strategy ie: show chapter 1 of LMS to isInstaStud:false 
@chrisjannenga @IsmaelPerezGit
> Implement is premium column for user

- src/Components/Main.js
it's working again - had to work out merge conflict from brandon's auth work
> Main: fixes router path for /chat

- .idea/workspace.xml
- src/Components/Forms/OnTheWeb.js
- src/Components/Forms/SignIn.js
- src/Components/Main.js
- src/Components/Pages/LandingPage.js
- src/Components/Reusable/AuthRedirect.js
- yarn.lock
Not sure if i'm making things better or worse. Seems to be working properly though.
> Login: fixed login issues.
